#ifndef SWMMOPENMINOGLOBALS_GLOBAL_H
#define SWMMOPENMINOGLOBALS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SWMMOPENMINOGLOBALS_LIB
# define SWMMOPENMINOGLOBALS_EXPORT Q_DECL_EXPORT
#else
# define SWMMOPENMINOGLOBALS_EXPORT Q_DECL_IMPORT
#endif

#endif // SWMMOPENMINOGLOBALS_GLOBAL_H
