#ifndef SWMMOPENMI_GLOBAL_H
#define SWMMOPENMI_GLOBAL_H

//#include <QtCore/qglobal.h>

#ifdef SWMMOPENMI_LIB
# define SWMMOPENMI_EXPORT Q_DECL_EXPORT
#else
# define SWMMOPENMI_EXPORT Q_DECL_IMPORT
#endif

#endif // SWMMOPENMI_GLOBAL_H
