use feature 'say';

@varNames = 
	(
	'Finp',
    'Fout',
    'Frpt',
    'Fclimate',
    'Frain',
    'Frunoff',
    'Frdii',
    'Fhotstart1',
    'Fhotstart2',
    'Finflows',
    'Foutflows',
    'Nperiods',
    'StepCount',
    'NonConvergeCount',
    'Msg',
    'Title',
    'TempDir',
    'RptFlags',
    'Nobjects',
    'Nnodes',
	'Nlinks',
	'UnitSystem',
	'FlowUnits',
	'InfilModel',
	'RouteModel',               
	'ForceMainEqn',             
	'LinkOffsets',              
	'AllowPonding',             
	'InertDamping',             
	'NormalFlowLtd',            
	'SlopeWeighting',           
	'Compatibility',            
	'SkipSteadyState',          
	'IgnoreRainfall',           
	'IgnoreRDII',               
	'IgnoreSnowmelt',           
	'IgnoreGwater',             
	'IgnoreRouting',            
	'IgnoreQuality',            
	'ErrorCode',                
	'WarningCode',              
	'WetStep',                  
	'DryStep',                  
	'ReportStep',               
	'SweepStart',               
	'SweepEnd',                 
	'MaxTrials',
	'RouteStep',
    'LengtheningStep',          
    'StartDryDays',             
    'CourantFactor',            
	'MinSurfArea',              
    'MinSlope',                 
    'RunoffError',              
    'GwaterError',              
    'FlowError',                
    'QualError',                
    'HeadTol',                  
    'SysFlowTol',               
    'LatFlowTol',               
 	'StartDate',                
    'StartTime',                
    'StartDateTime',            
    'EndDate',                  
    'EndTime',                  
    'EndDateTime',              
    'ReportStartDate',          
    'ReportStartTime',          
    'ReportStart',              
    'ReportTime',               
    'OldRunoffTime',            
    'NewRunoffTime',            
    'OldRoutingTime',           
    'NewRoutingTime',          
    'TotalDuration',            
    'Temp',                     
    'Evap',                     
    'Wind',                     
    'Snow',                     
    'Snowmelt',                 
    'Gage',                     
    'Subcatch',                 
    'Aquifer',                  
    'UnitHyd',                  
    'Node',                     
    'Outfall',                  
    'Divider',                  
    'Storage',                  
    'Link',                     
    'Conduit',                  
    'Pump',                     
    'Orifice',                  
    'Weir',                     
    'Outlet',                   
    'Pollut',                   
    'Landuse',                  
    'Pattern',                  
    'Curve',                    
    'Tseries',                  
    'Transect',                 
    'Shape'
);


foreach my $var (@varNames){
	print "Replacing all occurrences of '${var}' with 'project->${var}'... ";	
	# `sed -i '' 's/\<$var\>/project->$var/' ./SWMMOpenMINoGlobals/*`;

	`sed -i '' 's/[[:<:]]${var}[[:>:]]/project->${var}/' ./SWMMOpenMINoGlobals/*`;

	say 'done';

}

